#ifndef AMI_AIRPRINT_VERSION_H
#define AMI_AIRPRINT_VERSION_H

/*
 * AmiAirPrint package / preferences version.
 *
 * Version 1.2 adds selectable PWG/PDF/PostScript output, capability-backed
 * paper source and resolution controls, real PWG duplex submission and an
 * SSDP discovery fallback. The classic PRT:/CMD_WRITE and PersonalPaint paths
 * remain available and PWG/one-sided stays the backward-compatible default.
 */
#define AMIAIRPRINT_VERSION_MAJOR 1
#define AMIAIRPRINT_VERSION_MINOR 2
#define AMIAIRPRINT_VERSION_TEXT "1.2"
#define AMIAIRPRINT_VERSION_DATE "28.8.2026"
#define AMIAIRPRINT_VERSION_DATE_LONG "28 Aug 2026"

#define AMIAIRPRINT_PREFS_VERSION_MAJOR AMIAIRPRINT_VERSION_MAJOR
#define AMIAIRPRINT_PREFS_VERSION_MINOR AMIAIRPRINT_VERSION_MINOR
#define AMIAIRPRINT_PREFS_VERSION_TEXT AMIAIRPRINT_VERSION_TEXT
#define AMIAIRPRINT_PREFS_VERSION_DATE AMIAIRPRINT_VERSION_DATE
#define AMIAIRPRINT_PREFS_VERSION_DATE_LONG AMIAIRPRINT_VERSION_DATE_LONG

#define AMIAIRPRINT_CORE_VERSION_MAJOR 1
#define AMIAIRPRINT_CORE_VERSION_MINOR 2
#define AMIAIRPRINT_CORE_VERSION_TEXT "1.2"
#define AMIAIRPRINT_CORE_VERSION_DATE "28.8.2026"
#define AMIAIRPRINT_CORE_VERSION_DATE_LONG "28 Aug 2026"

#endif
